Fixes per PR

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,8 +8,8 @@ branding:
 inputs:
   releaseNotesDirectory:
     description: "The path to the release notes directory"
-    default: ./docs/releases
-  nextVersion:
+    default: ${{ github.workspace }}/docs/releases
+  version:
     description: "The version to validate"
     required: true
 
@@ -27,22 +27,22 @@ runs:
       id: set-path
       shell: bash
       run: |
-        FILE_PATH="${{ inputs.releaseNotesDirectory }}/${{ inputs.nextVersion }}.md"
+        FILE_PATH="${{ inputs.releaseNotesDirectory }}/${{ inputs.version }}.md"
         echo "file_path=$FILE_PATH" >> $GITHUB_OUTPUT
         
     - name: Validate Release Notes are Present
       shell: bash
       run: |
         if [ ! -f "${{ steps.set-path.outputs.file_path }}" ]; then
-          echo "Release notes for ${{ inputs.nextVersion }} are missing. Please create a release notes file at ${{ steps.set-path.outputs.file_path }}"
+          echo "Release notes for ${{ inputs.version }} are missing. Please create a release notes file at ${{ steps.set-path.outputs.file_path }}"
           exit 1
         fi
 
     - name: Validate Formatting
       shell: bash
       run: |
-        if ! grep -q "^# \[${{ inputs.nextVersion }}\](https://github.com/cloudzero/cloudzero-changelog-release-notes/compare/.*) ([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\})" ${{ steps.set-path.outputs.file_path }}; then
-            echo "Error: Version ${{ inputs.nextVersion }} does not have the correct title format \"# [${{ inputs.nextVersion }}](https://github.com/cloudzero/cloudzero-changelog-release-notes/compare/) - YYYY-MM-DD\""
+        if ! grep -q "^# \[${{ inputs.version }}\](https://github.com/cloudzero/cloudzero-changelog-release-notes/compare/.*) ([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\})" ${{ steps.set-path.outputs.file_path }}; then
+            echo "Error: Version ${{ inputs.version }} does not have the correct title format \"# [${{ inputs.version }}](https://github.com/cloudzero/cloudzero-changelog-release-notes/compare/) - YYYY-MM-DD\""
             exit 1
         fi
     
